//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helvartis.SQLServerDump.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helvartis.SQLServerDump.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is more than one local instance. Please use --server-name to select the instance to use..
        /// </summary>
        internal static string ErrMoreThanOneLocalInstance {
            get {
                return ResourceManager.GetString("ErrMoreThanOneLocalInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no local instance running.
        /// </summary>
        internal static string ErrNoLocalInstance {
            get {
                return ResourceManager.GetString("ErrNoLocalInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sqlserverdump version {version}
        ///By Daniel Jann, inspired by the mysqldump utility by
        ///Igor Romanenko, Monty, Jani &amp; Sinisa.
        ///This software comes with ABSOLUTELY NO WARRANTY. This is free software,
        ///and you are welcome to modify and redistribute it under the GPL license.
        ///
        ///Dumping structure and contents of SQL Server databases and objects.
        ///{usage}
        ///
        ///The following options may be given:
        ///--all-databases       Dump all the databases. This will be same as --databases
        ///                      with all databases [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage: sqlserverdump [OPTIONS] database [OBJECT1 [OBJECT2 [...]]]
        ///OR     sqlserverdump [OPTIONS] --databases [OPTIONS] DB1 [DB2 [DB3 [...]]]
        ///OR     sqlserverdump [OPTIONS] --all-databases [OPTIONS].
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For more options, use sqlserverdump --help.
        /// </summary>
        internal static string Usage_more {
            get {
                return ResourceManager.GetString("Usage_more", resourceCulture);
            }
        }
    }
}
